CREATE TABLE writers(
  id BIGINT NOT NULL PRIMARY KEY,
  full_name VARCHAR(50) NOT NULL,
  nick_name VARCHAR(25),
  nationality VARCHAR(50)
);

CREATE TABLE books(
  id BIGINT NOT NULL PRIMARY KEY,
  title VARCHAR(100) NOT NULL,
  synopsis VARCHAR(500),
  publishing_company VARCHAR(50),
  edition SMALLINT,
  year SMALLINT,
  language VARCHAR(20) NOT NULL,
  pages SMALLINT,
  height REAL,
  width REAL,
  weight REAL
);

CREATE TABLE writers_books(
  writer_id BIGINT NOT NULL,
  book_id BIGINT NOT NULL,
  CONSTRAINT writers_books_writers_fk FOREIGN KEY(writer_id) REFERENCES writers(id),
  CONSTRAINT writers_books_books_fk FOREIGN KEY(book_id) REFERENCES books(id)
);

CREATE TABLE images(
  id BIGINT NOT NULL PRIMARY KEY,
  book_id BIGINT NOT NULL,
  file_path VARCHAR(300) NOT NULL,
  CONSTRAINT images_books_fk FOREIGN KEY(book_id) REFERENCES books(id)
);

CREATE TABLE bookcase(
  id BIGINT NOT NULL PRIMARY KEY,
  book_id BIGINT NOT NULL,
  comments VARCHAR(300),
  read BOOLEAN NOT NULL,
  gender VARCHAR(25),
  CONSTRAINT bookcase_books_fk FOREIGN KEY(book_id) REFERENCES books(id)
);

CREATE SEQUENCE writers_seq START WITH 1 INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 NO CYCLE;
CREATE SEQUENCE books_seq START WITH 1 INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 NO CYCLE;
CREATE SEQUENCE images_seq START WITH 1 INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 NO CYCLE;
CREATE SEQUENCE bookcase_seq START WITH 1 INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 NO CYCLE;
