# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 717a76b57b3315d30c08a569bc20ba05ee2fc534ddd25f6789d8ce80b16939ad98de587848c0525b396d0beb8ed83525e25c1dc5407438d5e8ad6088f59cb10b

test:
  secret_key_base: b448dc4d5ccc2907db82d43a8713b937c78c7f1ce918264095c6adcc8aac0f295b8ef4eca8142bf1caeb77db3ae60a3e964cc1d6d0b02f64fd389722b5ca292d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
